In [26]:
import pandas as pd

In [27]:
t=pd.read_csv('cancer issue.csv')
t

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [28]:
t.shape # no of rows and columns

(17686, 16)

In [29]:
t.head(4)  #first four rows data

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South

In [30]:
t.tail(4) #last 4 rows data

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [31]:
t.sample(6) #random 6 rows data

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
3730,3731,55,Female,Hispanic,39.5,Former Smoker,No,Skin,II,1.5,Surgery,No Response,101,No,BRCA1,North
652,653,88,Female,Asian,33.5,Non-Smoker,Yes,Colon,III,6.3,Surgery,No Response,29,No,KRAS,West
3793,3794,87,Female,Other,29.6,Non-Smoker,No,Lung,II,7.3,Surgery,No Response,114,No,NaN,West
1233,1234,38,Female,Caucasian,35.7,Former Smoker,No,Colon,IV,7.5,Combination Therapy,No Response,90,No,EGFR,West
13400,13401,90,Female,African American,38.5,Non-Smoker,Yes,Lung,II,3.1,Surgery,Complete Remission,101,No,BRCA1,East
2007,2008,52,Male,African American,24.2,Non-Smoker,Yes,Skin,III,4.0,Surgery,Complete Remission,106,No,EGFR,South

In [32]:
t.info()        # information on data type and null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17686 entries, 0 to 17685
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          17686 non-null  int64
 1   Age                17686 non-null  int64
 2   Gender             17686 non-null  object
 3   Race/Ethnicity     17686 non-null  object
 4   BMI                17686 non-null  float64
 5   SmokingStatus      17686 non-null  object
 6   FamilyHistory      17686 non-null  object
 7   CancerType         17686 non-null  object
 8   Stage              17686 non-null  object
 9   TumorSize          17686 non-null  float64
 10  TreatmentType      17686 non-null  object
 11  TreatmentResponse  17686 non-null  object
 12  SurvivalMonths     17686 non-null  int64
 13  Recurrence         17686 non-null  object
 14  GeneticMarker      13360 non-null  object
 15  HospitalRegion     17686 non-null  object
dtypes: float64(2), int64(3), object(11)
memory usage: 2.2+ MB

In [33]:
t.columns

Index(['PatientID', 'Age', 'Gender', 'Race/Ethnicity', 'BMI', 'SmokingStatus',
       'FamilyHistory', 'CancerType', 'Stage', 'TumorSize', 'TreatmentType',
       'TreatmentResponse', 'SurvivalMonths', 'Recurrence', 'GeneticMarker',
       'HospitalRegion'],
      dtype='object')

In [34]:
t.isnull().sum()

PatientID               0
Age                     0
Gender                  0
Race/Ethnicity          0
BMI                     0
SmokingStatus           0
FamilyHistory           0
CancerType              0
Stage                   0
TumorSize               0
TreatmentType           0
TreatmentResponse       0
SurvivalMonths          0
Recurrence              0
GeneticMarker        4326
HospitalRegion          0
dtype: int64

In [35]:
t.describe().T

,count,mean,std,min,25%,50%,75%,max
PatientID,17686.0,8843.500000,5105.652766,1.0,4422.25,8843.5,13264.75,17686.0
Age,17686.0,53.758396,21.079473,18.0,35.00,54.0,72.00,90.0
BMI,17686.0,29.253805,6.203575,18.5,23.90,29.2,34.60,40.0
TumorSize,17686.0,5.499751,2.603107,1.0,3.30,5.5,7.70,10.0
SurvivalMonths,17686.0,60.387821,34.794859,1.0,30.00,60.0,91.00,120.0

In [36]:
t.describe(include=object).T

                   count unique                top  freq
Gender             17686      2             Female  8930
Race/Ethnicity     17686      5              Asian  3599
SmokingStatus      17686      3      Former Smoker  5915
FamilyHistory      17686      2                Yes  8863
CancerType         17686      6               Skin  2980
Stage              17686      4                  I  4471
TreatmentType      17686      4            Surgery  4493
TreatmentResponse  17686      3  Partial Remission  5951
Recurrence         17686      2                 No  8870
GeneticMarker      13360      3              BRCA1  4478
HospitalRegion     17686      4               East  4497

In [37]:
t.describe().style.background_gradient('rainbow')  # change background style

In [38]:
t.dtypes   #check data types

PatientID              int64
Age                    int64
Gender                object
Race/Ethnicity        object
BMI                  float64
SmokingStatus         object
FamilyHistory         object
CancerType            object
Stage                 object
TumorSize            float64
TreatmentType         object
TreatmentResponse     object
SurvivalMonths         int64
Recurrence            object
GeneticMarker         object
HospitalRegion        object
dtype: object

In [39]:
t.select_dtypes(include='object')  # take only object data type columns

,Gender,Race/Ethnicity,SmokingStatus,FamilyHistory,CancerType,Stage,TreatmentType,TreatmentResponse,Recurrence,GeneticMarker,HospitalRegion
0,Female,Other,Smoker,Yes,Breast,II,Combination Therapy,No Response,Yes,NaN,South
1,Male,Caucasian,Former Smoker,Yes,Colon,IV,Surgery,No Response,Yes,BRCA1,West
2,Male,Asian,Smoker,Yes,Breast,III,Combination Therapy,Complete Remission,Yes,BRCA1,West
3,Male,Asian,Former Smoker,Yes,Prostate,II,Radiation,Partial Remission,No,KRAS,South
4,Male,Caucasian,Smoker,Yes,Lung,IV,Radiation,No Response,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...
17681,Male,Caucasian,Non-Smoker,No,Skin,I,Radiation,Complete Remission,No,EGFR,South
17682,Female,Other,Smoker,No,Breast,I,Combination Therapy,Partial Remission,No,BRCA1,West
17683,Male,Caucasian,Former Smoker,No,Prostate,II,Chemotherapy,No Response,No,NaN,South
17684,Female,African American,Former Smoker,Yes,Prostate,III,Surgery,No Response,No,KRAS,East
17685,Female,African American,Non-Smoker,Yes,Breast,III,Surgery,Complete Remission,No,NaN,East

In [40]:
t.select_dtypes(include='int')  # take only int data type columns

       PatientID  Age  SurvivalMonths
0              1   80             103
1              2   76              14
2              3   69              61
3              4   77              64
4              5   89              82
...          ...  ...             ...
17681      17682   48              49
17682      17683   83              61
17683      17684   86              50
17684      17685   77              23
17685      17686   80              30

[17686 rows x 3 columns]

In [41]:
t.select_dtypes(include='float')  # take only float data type columns

        BMI  TumorSize
0      23.3        1.7
1      22.4        4.7
2      21.5        8.3
3      30.4        1.7
4      20.9        7.4
...     ...        ...
17681  35.3        4.9
17682  32.5        8.8
17683  39.8        8.6
17684  37.9        1.8
17685  29.3        9.1

[17686 rows x 2 columns]

In [42]:
t

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [44]:
t[t['Age']>45]  # print the patient data whose age is >45

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [ ]:
#print the male and female patients count

In [46]:
t['CancerType'].unique()   # What are the cancer types?

array(['Breast', 'Colon', 'Prostate', 'Lung', 'Leukemia', 'Skin'],
      dtype=object)

In [48]:
t['CancerType'].nunique()   #count of cancer type

6

In [49]:
t['TreatmentType'].unique() # what are the treatment types?

array(['Combination Therapy', 'Surgery', 'Radiation', 'Chemotherapy'],
      dtype=object)

In [50]:
t['TreatmentType'].nunique()  #count of treatment types

4

In [52]:
t['CancerType'].value_counts()  # count of each cancer type patients.

CancerType
Skin        2980
Leukemia    2957
Lung        2939
Breast      2938
Prostate    2938
Colon       2934
Name: count, dtype: int64

In [63]:
t['TumorSize'].max()  # maximum tumor size

10.0

In [64]:
t['TumorSize'].min()  # minimum tumor size

1.0

In [58]:
t['TumorSize'].mean().round()

5.0

In [61]:
t.groupby('Gender')['TumorSize'].max()  #maximum tumor size in female and male

Gender
Female    10.0
Male      10.0
Name: TumorSize, dtype: float64

In [62]:
t.groupby('Gender')['TumorSize'].min() # min tumor size in female and male

Gender
Female    1.0
Male      1.0
Name: TumorSize, dtype: float64

In [67]:
t.groupby('Gender')['SmokingStatus'].value_counts()   # gender wise smoking ststus

Gender  SmokingStatus
Female  Former Smoker    3024
        Non-Smoker       2992
        Smoker           2914
Male    Smoker           2946
        Non-Smoker       2919
        Former Smoker    2891
Name: count, dtype: int64

In [80]:
t[t['Stage']=='IV'].value_counts().sum()   # stage four cancer patients in all types

3314

In [93]:
t.groupby('CancerType')['SmokingStatus'].value_counts()       #cancer type and smoking status wise count

CancerType  SmokingStatus
Breast      Non-Smoker       1010
            Former Smoker     985
            Smoker            943
Colon       Former Smoker    1002
            Smoker            972
            Non-Smoker        960
Leukemia    Non-Smoker        999
            Former Smoker     988
            Smoker            970
Lung        Smoker            997
            Non-Smoker        980
            Former Smoker     962
Prostate    Non-Smoker        985
            Former Smoker     977
            Smoker            976
Skin        Smoker           1002
            Former Smoker    1001
            Non-Smoker        977
Name: count, dtype: int64

In [94]:
t

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [96]:
t[t['CancerType']=='Breast']   #select the patients who have breast cancer

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
6,7,60,Female,Hispanic,26.3,Former Smoker,Yes,Breast,I,5.3,Surgery,Partial Remission,88,No,KRAS,West
7,8,54,Female,African American,25.9,Former Smoker,Yes,Breast,III,10.0,Combination Therapy,Partial Remission,95,No,BRCA1,East
19,20,59,Female,Other,31.8,Non-Smoker,Yes,Breast,III,6.1,Radiation,No Response,108,No,NaN,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17664,17665,28,Female,African American,29.8,Non-Smoker,No,Breast,I,7.5,Chemotherapy,Partial Remission,30,Yes,EGFR,East
17673,17674,53,Female,Asian,29.9,Former Smoker,Yes,Breast,III,3.9,Radiation,Complete Remission,67,No,KRAS,East
17678,17679,86,Male,Asian,35.9,Former Smoker,No,Breast,II,7.9,Combination Therapy,Complete Remission,93,Yes,BRCA1,West
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [99]:
t.loc[:,['Age','BMI','TumorSize','SurvivalMonths']].max()

Age                90.0
BMI                40.0
TumorSize          10.0
SurvivalMonths    120.0
dtype: float64

In [115]:
t.iloc[:,[1,4,9,12]]

       Age   BMI  TumorSize  SurvivalMonths
0       80  23.3        1.7             103
1       76  22.4        4.7              14
2       69  21.5        8.3              61
3       77  30.4        1.7              64
4       89  20.9        7.4              82
...    ...   ...        ...             ...
17681   48  35.3        4.9              49
17682   83  32.5        8.8              61
17683   86  39.8        8.6              50
17684   77  37.9        1.8              23
17685   80  29.3        9.1              30

[17686 rows x 4 columns]

In [113]:
t.iloc[:,[1,4,9,12]].mean()

Age               53.758396
BMI               29.253805
TumorSize          5.499751
SurvivalMonths    60.387821
dtype: float64

In [114]:
t.iloc[:,[1,4,9,12]].max()

Age                90.0
BMI                40.0
TumorSize          10.0
SurvivalMonths    120.0
dtype: float64

In [117]:
t.iloc[:,[1,4,9,12]].min()

Age               18.0
BMI               18.5
TumorSize          1.0
SurvivalMonths     1.0
dtype: float64